### ISSUE TITLE
list it at @APIs-guru

### ISSUE THREAD

**Issue by jgcmarins** [matheusrocha89/graphql-camara-deputados#2]
add this repo to https://github.com/APIs-guru/graphql-apis \o/

**Comment by matheusrocha89** [comment]
Nice, I will do right now

**Comment by matheusrocha89** [comment]
Just open the PR there

**Comment by matheusrocha89** [comment]
Already created and merged.
https://github.com/APIs-guru/graphql-apis/pull/30
